version: '3.4'

services:

  sqldata:
    image: "sqlgateway"
    volumes:
     - mssqldata:/var/opt/mssql
    environment:
      SA_PASSWORD: "12Password12"
      ACCEPT_EULA: "Y"
    ports:
     - "1433:1433"
    networks:
     - mygateway

  ckpaymentgateway:
    image: ${DOCKER_REGISTRY-}ckpaymentgateway
    build:
      context: .
      dockerfile: CKPaymentGateway\Dockerfile
    depends_on:
     - ckbank
    ports:
     - "62849:443"
     - "62848:80"
    networks:
     - mygateway

  ckmerchant:
    image: ${DOCKER_REGISTRY-}ckmerchant
    build:
      context: .
      dockerfile: CKMerchant\Dockerfile
    depends_on:
     - sqldata
    ports:
     - "62852:443"
     - "62851:80"
    networks:
     - mygateway
    links:
     - "sqldata:database"

  ckbank:
    image: ${DOCKER_REGISTRY-}ckbank
    build:
      context: .
      dockerfile: CKBank\Dockerfile
    ports:
     - "62854:443"
     - "62853:80"
    networks:
     - mygateway


networks:
  mygateway:


volumes:
  mssqldata: